SportStore/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SportStore.Models {
    public class ProductViewModel {
        public int ProductID { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [Range(0.01, double.MaxValue)]
        public decimal Price { get; set; }

        [Required]
        public string Category { set; get; }
    }
}

SportStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SportStore.Domain;
using SportStore.Domain.Entities;
using SportStore.Infrastructure.BusinessLogic;
using SportStore.Infrastructure.WebCommon;
using SportStore.Infrastructure.WebCommon.Helpers;
using SportStore.Models;

namespace SportStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartLogic _cartLogic;
        private readonly IRepository<Product> _productRepository;
        private readonly IStorage<CartViewModel> _cartStorage;
        private readonly IMapper _mapper;
        private const int _pageSize = 4;

        public CartController(ICartLogic cartLogic, IRepository<Product> productRepository, IMapper mapper, IStorage<CartViewModel> cartStorage) {
            _cartLogic = cartLogic;
            _cartStorage = cartStorage;
            _productRepository = productRepository;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index(string returnUrl) {
            var cart = _cartStorage.GetItem();
            cart.ReturnUrl = returnUrl;
            cart.TotalValue = _cartLogic.CalcTotalValue(cart);

            return View(cart);
        }

        [HttpPost]
        public RedirectToActionResult AddToCart(int productId, string returnUrl) {
            var product = _productRepository.GetAll()
                .FirstOrDefault(p => p.ProductID == productId);
            var productVm = _mapper.Map<ProductViewModel>(product);

            if (product != null) {
                CartViewModel cart = _cartStorage.GetItem();
                _cartLogic.AddItem(cart, productVm, 1);
                _cartStorage.Save(cart);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl) {
            var product = _productRepository.GetAll()
                .FirstOrDefault(p => p.ProductID == productId);
            var productVm = _mapper.Map<ProductViewModel>(product);

            if (product != null) {
                CartViewModel cart = _cartStorage.GetItem();
                _cartLogic.RemoveItem(cart, productVm);
                _cartStorage.Save(cart);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportStore/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SportStore.Domain;
using SportStore.Domain.Entities;
using SportStore.Infrastructure.BusinessLogic;
using SportStore.Models;
using System.Collections.Generic;
using System.Linq;

namespace SportStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly ICartLogic _cartLogic;
        private readonly IRepository<Product> _productRepository;
        private readonly IMapper _mapper;
        private const int _pageSize = 4;

        public ProductController(ICartLogic cartLogic, IRepository<Product> productRepository, IMapper mapper) {
            _cartLogic = cartLogic;
            _productRepository = productRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult List(string category, int productPage = 1) {            
            var repoProducts = _productRepository.GetFilteredProduct(category, productPage, _pageSize);
            var modelProducts = _mapper.Map<IEnumerable<ProductViewModel>>(repoProducts);

            var totalProduct = category == null ? _productRepository.GetAll().Count() : modelProducts.Count();

            var viewModel = new ProductListViewModel {
                CurrentCategory = category,
                Products = modelProducts,
                PagingInfo = new PagingInfo {
                    CurrentPage = productPage,
                    ItemsPerPage = _pageSize,
                    TotalItems = totalProduct
                }
            };
            
            return View(viewModel);
        }
    }
}

SportStore/Views/Product/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
</body>
</html>

SportStore/Views/Product/List.cshtml
@model ProductListViewModel

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

@foreach (var product in Model.Products) {
    <partial name="ProductSummaryPartial" model="@product"/>
}

<div 
    page-model="@Model.PagingInfo" 
    page-action="List"
    page-url-category="@Model.CurrentCategory"
    page-classes-enabled="true"
    page-class="btn"
    page-class-normal="btn-secondary"
    page-class-selected="btn-primary" class="btn-group pull-right m-1">
</div>

SportStore/Views/Product/ProductSummaryPartial.cshtml
@model ProductViewModel


<div class="card card-header-pills m-1 p-1">
    <div class="bg-light p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right;">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductID" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl" 
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>