SportStore/Infrastructure/WebCommon/Helpers/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportStore.Domain;
using SportStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportStore.Infrastructure.WebCommon.Helpers {
    public class NavigationMenuViewComponent : ViewComponent {

        private readonly IRepository<Product> _productRepository;

        public NavigationMenuViewComponent(IRepository<Product> repository) {
            _productRepository = repository;
        }

        public IViewComponentResult Invoke() {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            var categories = _productRepository.FilterFields<string>(x => x.Category).Distinct().OrderBy(x => x);
            return View(categories);
        }
    }
}

SportStore/Infrastructure/WebCommon/Widget/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportStore.Infrastructure.BusinessLogic;
using SportStore.Models;

namespace SportStore.Infrastructure.WebCommon.Widget {
    public class CartSummaryViewComponent : ViewComponent {
        private readonly IStorage<CartViewModel> _cartStorage;
        private readonly ICartLogic _cartLogic;

        public CartSummaryViewComponent(IStorage<CartViewModel> cartStorage, ICartLogic cartLogic) {
            _cartStorage = cartStorage;
            _cartLogic = cartLogic;
        }

        public IViewComponentResult Invoke() {
            var cart = _cartStorage.GetItem();
            cart.TotalValue = _cartLogic.CalcTotalValue(cart);

            return View(cart);
        }
    }
}

SportStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
</head>
<body class="m-1 p-1">
    <div class="bg-info p-2 row">
        <div class="col">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-sm btn-primary" asp-action="LogOut" asp-controller="Account">LogOut</a>
        </div>
    </div>

    @if (TempData["message"] != null) {
        <div class="alert alert-success mt-1">@TempData["message"]</div>
    }

    @RenderBody()

</body>
</html>

SportStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/**/*.min.css" asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css"/>
</head>
<body>
    <div class="navbar navbar-nav bg-info" role="navigation">
        <div class="row">
            <a class="col navbar-brand" href="#">SPORTS STORE</a>
            <div class="col-4 text-right">
                @await Component.InvokeAsync("CartSummary")
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>